# Geral
spring:
  application:
    name: Cadastro-api
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/ead
      username: postgres
      password: 123456
  jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
